### ISSUE TITLE
Multiple multipleSelect conflict when single=true option set

### ISSUE THREAD

**Issue by esadun** [wenzhixin/multiple-select#169]
With 2 (or presumably more) multipleSelects on a page that all have the single=true option, choosing a new value from one dropdown clears the value already set in the other. After setting it again, the original multipleSelect loses its value in the same way, and so on. Changing either multipleSelect back to a standard implementation (without setting the single=true option) prevents the issue (but obviously isn't always possible).

**Comment by Jayeshecs** [comment]
I am facing the same issue and it seems that problem might be related to how jQuery selector is used e.g. in my case there are search criterias ...
[ search field1 |V] [equals |V] [Criteria1 drop down |V] [+] [-]

Problem happens when I add another line in which I select the search field 2 the operand drop down gets cleared ...

[ search field1 |V] [            |V] [Criteria2 drop down |V] [+] [-]
[ search field2 |V] [equals |V] [Criteria2 drop down |V] [+] [-]

I am trying to prepare a small HTML to replicate this issue as I cannot share the original code.

**Comment by morex87** [comment]
Same issue before..
I think I found a fix, replace those lines in file jquery.multiple.select.js..

line 73:
//html.push('[ul]');
html.push('[form][ul]');

line 88:
//html.push('[/ul]');
html.push('[/ul][/form]');

I'm using version 1.0.7 almost sure that will work on current version..
It works for me using more than one multipleSelect with single=true option

Best Regards!

**Comment by Jayeshecs** [comment]
Thank you morex :+1:

**Comment by wenzhixin** [comment]
Fixed this issue in the latest version, of course you can set  a name attribute to solve this issue in old version.
