### ISSUE TITLE
taking lots of time for drop down with more than 10000 elements.

### ISSUE THREAD

**Issue by incredibleat** [wenzhixin/multiple-select#307]
Hi All,

We are using JQuery v1.10.1 and jquery.multiple.select plugin for html ui development

Problem Statement : We are having HTML UI with more than 10000 data elements which we need to populate in Drop Down box (combo). These elements have Option Groups which contain sub multiple options.

e.g.``` Input Data <optgroup label="A"> <option value="100>100</option> <option value="200">200</option> </optgroup> <optgroup label="B"> <option value="300>300</option> </optgroup>```
Issue Observed : We are observing that when we tried to load these elements in drop down it takes considerable amount of time to render in drop down, sometimes pop up comes up asking if you wish to wait or kill. Sometimes it shows the element populated but any action further causes to hang the browser (chrome and firefox).

Below is the code snippet we have implemented to populate the drop down.

                   if ($('demo.select').length > 0) {
                        $.ajax({
                            url: 'http://localhost:8080/demo/getdata?',
                            type: 'GET'
                        }).done(function (result, textStatus, jqXHR) {
                                $('demo.select').append(result);
                                $('demo.select').multipleSelect({
                                    width: '400px',
                                    filter: true
                                });
                            }
                        );
                    }
We observed that multiselect takes considerable time to render the drop down which iterates through the 10k elements. We would like to know is there a better way of rendering the drop down box? Any suggestion will help.

Thanks

**Comment by leonceattolou** [comment]
Hi,
i have the save issue. I need to know if there is a way to filtered data directly from database and keep the way to have multiple select fonctionnality.
Best regard

**Comment by incredibleat** [comment]
@leonceattolou please suggest solution.

**Comment by leonceattolou** [comment]
Hi,
i solve it. You can see how i solve it below:
1- In the file multiple-select.js search 'that.filter();' and put before this instruction this : ' that.$el.trigger('change_custom');'
2- In your custom js file you can use this:
a-
$('multiple_select_selector').multipleSelect(option_selctor);
b-
$('multiple_select_selector')
 .bind
  (
     'change_custom',
     function() {
       $.ajax
	(
		{
			data	: {//your data },
			success	:
				function(data)
				{
				   //replace old select options by news
					$('selector').html
                                          (
						$(data).find('multiple_select_selector').html()
					  )
                                        ;
                            //copy search text to the new input search and instantiate the select multiple
					$search=$('.ms-search input').val();
				        $('multiple_select_selector').multipleSelect(option_selector);
					$('.ms-search input').val($search);
				}
		}
	);
});

**Comment by incredibleat** [comment]
thanks you so much @leonceattolou,
i really appreciate your solution..
with your provided solution you are displaying 10k records???
can you please elaborate your solution which will help me in clear understanding....
thanks in advance.

**Comment by leonceattolou** [comment]
Hi,
i have more than 10k records. I will share an elaborate solution for you soon.
Best regards

**Comment by incredibleat** [comment]
@leonceattolou thank u so much...
please i waiting for your solution...

**Comment by incredibleat** [comment]
Hello @leonceattolou i am waiting for your valuable reply....

Thanks in Advance

**Comment by leonceattolou** [comment]
Hi,
first time you should know that it is bad for performance, to load in the select multiple all your 1000 datas. Second time, you should understand the auto completion of multiple select filter of the plugin is not dynamic, so you will need to add custom script to make it dynamic. I mean by dynamic the fact that the select options must be loaded each time you enter a new character in your input search. Third time you need to bind a custom event to trigger your custom dynamic script, because the event keyup is already used in the plugin and we don't want to destroy the plugin.
So this is the solution:
1- Search in multiple-select file, where filter function is called ('that.filter();') and trigger your custom dynamic script before the call of filter function, by this way : 'that.$el.trigger('change_custom');'. Remember that 'that.$el' is your html select input.
2- Write you PHP script to get the 10 first database result from words entered in the select multiple input search. For instance i need to filter people from their first name, last name, and their organization's name:
"WHERE MATCH (t1.nom,t1.prenom,t1.societe) AGAINST ('thierry*' IN BOOLEAN MODE) LIMIT	10"
3- write your html script. This is mine: 
<p class="saisie" id="recherche-clients_parent">
    <label class="champs_titre" for="recherche-clients">Clients</label>
    <select id="recherche-clients" multiple class="moyen" type="text" name="recherche[commande][clients][]"></select>
</p>
4- Write your custom js script in a separated file. This is mine:
var correspondance_select_options	=
			{
				'#recherche-clients':{width: 300,multiple: true,multipleWidth: 220,filter:	true,selectAll:true},
		...
			}
;
for	(id in correspondance_select_options)
	$(id).multipleSelect(correspondance_select_options[id]);
$('#recherche-clients')
    .bind
    (
	'change_custom',
	function()
	{
		$.ajax
		(
			{
				data	:
				{
					'identite'	:	$('#recherche-clients_parent input').val()
				},
				success	:
					function(donnees)
					{
						var
							recherche_clients_option	=	$(donnees).find('#recherche-clients').html();
						$('#recherche-clients').html(recherche_clients_option);
						$saisie	=	$('.ms-search input').val();
						$('#recherche-clients').multipleSelect(correspondance_select_options['#recherche-clients']);
						$('.ms-search input').val($saisie);
						if	(recherche_clients_option=='')
							$('#recherche-clients').closest('p.saisie').find('.ms-no-results').attr('style','display:block');
					},
							error	:
								function()
								{
									ecrire_message('Une erreur est survenue !');
								}
						}
					)
					;
				}
			)
		;

Good luck.
Best regards

**Comment by incredibleat** [comment]
@leonceattolou i solved it...did customization in plugin.so it works as we expecting...now working with 14k elements...

Thanks

**Comment by BurhanNoori** [comment]
> @leonceattolou i solved it...did customization in plugin.so it works as we expecting...now working with 14k elements...
> 
> Thanks

Hi @atulwagare,

Can you please tell what customization you made. I am also facing the same issue.
