### ISSUE TITLE
oprgroups and countSelected problem

### ISSUE THREAD

**Issue by max-mykhailenko** [wenzhixin/multiple-select#67]
minumimCountSelected and countSelected don't work when use optgroups

**Comment by andreasringdal** [comment]
Shouldn't this be listed as bug and not enhancement?

**Comment by eoutvik** [comment]
Bug caused by getSelect('text') only returns array of optgroups when in use (line 476).
Workaround: 
```
$('select').multipleSelect({
  displayValues: true,
  minimumCountSelected: 0
})
```
This will only display number of selected elements (1 of 18 selected), not their text label.

**Comment by athill** [comment]
Can countSelected be modified to accept a function that returns a string? I'd like to handle my own display.

**Comment by fixwa** [comment]
I'm also having this problem. 
Any workaround or ideas?

**Comment by BlakeTsao** [comment]
modify the code in "update:" part
we can add the code to get the real countSelected number in oprgroups:
`
var selects = this.options.displayValues ? this.getSelects() : this.getSelects('getSelects');
var number = selects.length;
`
so, just modify the program logic of information presented

**Comment by developerNothing** [comment]
@BlakeTsao : What is the value of "de_selects"?

**Comment by BlakeTsao** [comment]
@developerNothing 
`var number = all_selects.length;`
I think it's a typo.

**Comment by ssttm169** [comment]
@eoutvik  You did a job, I have fixed my problem, thanks a lot.

**Comment by wenzhixin** [comment]
Fixed in the latest version.

* [minimumCountSelected](http://multiple-select.wenzhixin.net.cn/documentation/#options-minimumcountselected): [example](http://multiple-select.wenzhixin.net.cn/examples/#minimum-count-selected.html)
* [formatCountSelected](http://multiple-select.wenzhixin.net.cn/documentation/#localizations-formatcountselected): [example](http://multiple-select.wenzhixin.net.cn/examples/#i18n.html)
